// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapiASP.Models;

#nullable disable

namespace webapiASP.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("webapiASP.Models.Persons", b =>
                {
                    b.Property<int>("PersonsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonsId"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonsId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("webapiASP.Models.Prices", b =>
                {
                    b.Property<long>("PricesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PricesId"));

                    b.Property<double>("MinutePrice")
                        .HasColumnType("float");

                    b.Property<long>("ProgramCode")
                        .HasColumnType("bigint");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PricesId");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("webapiASP.Models.RegistrationProgram", b =>
                {
                    b.Property<long>("RegistrationProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RegistrationProgramId"));

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<long?>("PricesId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProgramCode")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ProgramDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Regularity")
                        .HasColumnType("int");

                    b.HasKey("RegistrationProgramId");

                    b.HasIndex("PricesId");

                    b.ToTable("RegistrationProgram");
                });

            modelBuilder.Entity("webapiASP.Models.RegistrationProgram", b =>
                {
                    b.HasOne("webapiASP.Models.Prices", "Prices")
                        .WithMany("registrationPrograms")
                        .HasForeignKey("PricesId");

                    b.Navigation("Prices");
                });

            modelBuilder.Entity("webapiASP.Models.Prices", b =>
                {
                    b.Navigation("registrationPrograms");
                });
#pragma warning restore 612, 618
        }
    }
}
